.TH "blocks/manu343726/turbo_computing Directory Reference" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blocks/manu343726/turbo_computing Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdecimal\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfixed_point\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfloat\&.hpp\fP"
.br
.in -1c
