.TH "build Directory Reference" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCMakeFiles\fP"
.br
.ti -1c
.RI "directory \fBDebug\fP"
.br
.ti -1c
.RI "directory \fBRelease\fP"
.br
.in -1c
