.TH "tml::impl::function_signature< F >::signature_extractor< R(C::*)(ARGS...)>" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::function_signature< F >::signature_extractor< R(C::*)(ARGS...)> \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::impl::function_signature_holder< R, ARGS\&.\&.\&.>\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename F>template<typename C, typename R, typename\&.\&.\&. ARGS>struct tml::impl::function_signature< F >::signature_extractor< R(C::*)(ARGS\&.\&.\&.)>"

.PP
Definition at line 106 of file type_traits\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
