.TH "tml::add< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::add< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > > \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBadder\fP"
.br
.ti -1c
.RI "struct \fBadder< m1, m2, sign, sign >\fP"
.br
.ti -1c
.RI "struct \fBadder< m1, m2, tml::floating::sign_t::negative, tml::floating::sign_t::positive >\fP"
.br
.ti -1c
.RI "struct \fBadder< m1, m2, tml::floating::sign_t::positive, tml::floating::sign_t::negative >\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBdlhs\fP = tml::floating::shift< \fBtml::floating::number\fP< S_LHS, E_LHS, M_LHS >, tml::Int<-1 >>"
.br
.ti -1c
.RI "using \fBdrhs\fP = tml::floating::shift< \fBtml::floating::number\fP< S_RHS, E_RHS, M_RHS >, tml::Int<-1 >>"
.br
.ti -1c
.RI "using \fBdenorm_lhs\fP = tml::lconditional< tml::Bool<(diff< 0)>, \fBtml::lazy\fP< \fBtml::floating::func::shift\fP, dlhs, tml::Int< diff >>, dlhs >"
.br
.ti -1c
.RI "using \fBdenorm_rhs\fP = tml::lconditional< tml::Bool<(diff >=0)>, \fBtml::lazy\fP< \fBtml::floating::func::shift\fP, drhs, tml::Int<-diff >>, drhs >"
.br
.ti -1c
.RI "using \fBresult\fP = tml::floating::normalize< typename adder< denorm_lhs::mantissa, denorm_rhs::mantissa, S_LHS, S_RHS >::result >"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr const int \fBdiff\fP = E_LHS - E_RHS"
.br
.ti -1c
.RI "static constexpr const 
.br
tml::floating::exponent_t \fBresult_exponent\fP = (diff >= 0) ? dlhs::exponent : drhs::exponent"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<tml::floating::sign_t S_LHS, tml::floating::exponent_t E_LHS, tml::floating::mantissa_t M_LHS, tml::floating::sign_t S_RHS, tml::floating::exponent_t E_RHS, tml::floating::mantissa_t M_RHS>struct tml::add< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > >"

.PP
Definition at line 264 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
