.TH "tml::impl::dconditional< CONDITION, TRUE, FALSE >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::dconditional< CONDITION, TRUE, FALSE > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< TRUE >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename CONDITION, typename TRUE, typename FALSE>struct tml::impl::dconditional< CONDITION, TRUE, FALSE >"

.PP
Definition at line 53 of file control_structures\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
