.TH "tml::impl::map< T, tml::list< SEQUENCE...>, tml::empty_list >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::map< T, tml::list< SEQUENCE...>, tml::empty_list > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = \fBtml::list\fP< tml::eval< T, SEQUENCE >\&.\&.\&.>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTURBO_ENSURE_ALGEBRAIC_EVAL\fP (\fBresult\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename\&.\&.\&. SEQUENCE>struct tml::impl::map< T, tml::list< SEQUENCE\&.\&.\&.>, tml::empty_list >"

.PP
Definition at line 72 of file high_order_functions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
