.TH "tml::floating::impl::parse_float< CHARS >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::floating::impl::parse_float< CHARS > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBinput\fP = \fBtml::character_list\fP< CHARS\&.\&.\&.>"
.br
.ti -1c
.RI "using \fBinitial_parsing_state\fP = \fBparsing_data\fP< float_parsing_state::reading_sign, 0, 0, 0, 0 >"
.br
.ti -1c
.RI "using \fBparse_result\fP = tml::foldl< \fBtml::lazy\fP< \fBparse\fP >, \fBinitial_parsing_state\fP, \fBinput\fP >"
.br
.ti -1c
.RI "template<std::int64_t i> using \fBinteger\fP = typename \fBtml::floating::impl::integer\fP< i >::result"
.br
.ti -1c
.RI "using \fBinteger_part\fP = integer< parse_result::integer_part >"
.br
.ti -1c
.RI "using \fBdecimals\fP = integer< parse_result::decimals >"
.br
.ti -1c
.RI "using \fBbias\fP = tml::integral_constant< std::int64_t,(std::int64_t)(parse_result::heading_zeros+parse_result::decimals_count)>"
.br
.ti -1c
.RI "using \fBheading_zero_bias\fP = tml::eval< \fBtml::pow\fP< integer< 10 >, bias >>"
.br
.ti -1c
.RI "using \fBdecimals_value\fP = tml::eval< \fBtml::div\fP< decimals, heading_zero_bias >>"
.br
.ti -1c
.RI "using \fBresult\fP = tml::eval< \fBtml::add\fP< integer_part, decimals_value >>"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<char\&.\&.\&. CHARS>struct tml::floating::impl::parse_float< CHARS >"

.PP
Definition at line 763 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
