.TH "tml::impl::multi_let_currifier< ARGS >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::multi_let_currifier< ARGS > \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcurrify\fP"
.br
.ti -1c
.RI "struct \fBcurrify< list< CURRENT_VAR, VARS_TAIL\&.\&.\&.>, list< CURRENT_VAL, VALS_TAIL\&.\&.\&.>, nil >\fP"
.br
.ti -1c
.RI "struct \fBcurrify< list<>, list<>, SENTINEL >\fP"
.br
.ti -1c
.RI "struct \fBnil\fP"
.br
.ti -1c
.RI "struct \fBsplit_in_middle\fP"
.br
.ti -1c
.RI "struct \fBsplit_in_middle< tml::list< LEFT_LIST\&.\&.\&.>, tml::list< HEAD, TAIL\&.\&.\&.>, false >\fP"
.br
.ti -1c
.RI "struct \fBsplit_in_middle< tml::list< LEFT_LIST\&.\&.\&.>, tml::list< RIGHT_LIST\&.\&.\&.>, true >\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtarget\fP = tml::lists::back< ARGS >"
.br
.ti -1c
.RI "using \fBargs_without_expression\fP = tml::lists::pop_back< ARGS >"
.br
.ti -1c
.RI "using \fBvariables\fP = typename \fBsplit_in_middle\fP< \fBtml::empty_list\fP, args_without_expression, false >::variables"
.br
.ti -1c
.RI "using \fBvalues\fP = typename \fBsplit_in_middle\fP< \fBtml::empty_list\fP, args_without_expression, false >::values"
.br
.ti -1c
.RI "using \fBresult\fP = typename \fBcurrify\fP< variables, values >::result"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename ARGS>struct tml::impl::multi_let_currifier< ARGS >"

.PP
Definition at line 215 of file let_expressions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
