.TH "tml::impl::bind_call< tml::impl::bind< F, ARGS...>, CARGS...>" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::bind_call< tml::impl::bind< F, ARGS...>, CARGS...> \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBapply\fP"
.br
.ti -1c
.RI "struct \fBtransformation\fP"
.br
.ti -1c
.RI "struct \fBtransformation< tml::placeholder< INDEX > >\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBcall_args\fP = tml::transform< \fBtml::lazy\fP< transformation >, \fBtml::list\fP< ARGS\&.\&.\&.> >"
.br
.ti -1c
.RI "using \fBresult\fP = tml::eval< \fBtml::uncurry\fP< apply >, call_args >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F, typename\&.\&.\&. ARGS, typename\&.\&.\&. CARGS>struct tml::impl::bind_call< tml::impl::bind< F, ARGS\&.\&.\&.>, CARGS\&.\&.\&.>"

.PP
Definition at line 51 of file bind\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
