.TH "tml::impl::lambda_builder< tml::list< X, BODY > >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::lambda_builder< tml::list< X, BODY > > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< tml::impl::lambda< X, BODY > >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename X, typename BODY>struct tml::impl::lambda_builder< tml::list< X, BODY > >"

.PP
Definition at line 155 of file lambda\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
