.TH "tml::impl::function_signature_holder< R, ARGS >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::function_signature_holder< R, ARGS > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBreturn_type\fP = R"
.br
.ti -1c
.RI "using \fBargs\fP = \fBtml::list\fP< ARGS\&.\&.\&.>"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename R, typename\&.\&.\&. ARGS>struct tml::impl::function_signature_holder< R, ARGS >"

.PP
Definition at line 87 of file type_traits\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
