.TH "tml::add< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > >::adder< m1, m2, sign, sign >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::add< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > >::adder< m1, m2, sign, sign > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< tml::floating::number< sign, result_exponent, m1+m2 > >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<tml::floating::sign_t S_LHS, tml::floating::exponent_t E_LHS, tml::floating::mantissa_t M_LHS, tml::floating::sign_t S_RHS, tml::floating::exponent_t E_RHS, tml::floating::mantissa_t M_RHS>template<tml::floating::mantissa_t m1, tml::floating::mantissa_t m2, tml::floating::sign_t sign>struct tml::add< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > >::adder< m1, m2, sign, sign >"

.PP
Definition at line 294 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
