.TH "tml::util::func::size_of< T >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::util::func::size_of< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< tml::size_t< sizeof(T)> >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct tml::util::func::size_of< T >"

.PP
Definition at line 48 of file utility\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
