.TH "tml::runtime::illformed_call< F, E >::void_return" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::runtime::illformed_call< F, E >::void_return \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::runtime::chameleon\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename F, typename E>struct tml::runtime::illformed_call< F, E >::void_return"

.PP
Definition at line 77 of file illformed_call\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
