.TH "tml::impl::is_function_ptr_type< T >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::is_function_ptr_type< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct tml::impl::is_function_ptr_type< T >"

.PP
Definition at line 80 of file eval\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
