.TH "tml::impl::multi_let_currifier< ARGS >::split_in_middle< tml::list< LEFT_LIST...>, tml::list< HEAD, TAIL...>, false >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::multi_let_currifier< ARGS >::split_in_middle< tml::list< LEFT_LIST...>, tml::list< HEAD, TAIL...>, false > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBnext_call\fP = \fBsplit_in_middle\fP< \fBtml::list\fP< LEFT_LIST\&.\&.\&., HEAD >, \fBtml::list\fP< TAIL\&.\&.\&.>,(sizeof\&.\&.\&.(LEFT_LIST)+1)==sizeof\&.\&.\&.(TAIL)>"
.br
.ti -1c
.RI "using \fBvariables\fP = typename next_call::variables"
.br
.ti -1c
.RI "using \fBvalues\fP = typename next_call::values"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename ARGS>template<typename\&.\&.\&. LEFT_LIST, typename HEAD, typename\&.\&.\&. TAIL>struct tml::impl::multi_let_currifier< ARGS >::split_in_middle< tml::list< LEFT_LIST\&.\&.\&.>, tml::list< HEAD, TAIL\&.\&.\&.>, false >"

.PP
Definition at line 241 of file let_expressions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
