.TH "tml::floating::impl::shift< F, COUNT >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::floating::impl::shift< F, COUNT > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = \fBtml::floating::number\fP< F::sign, exponent, mantissa >"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr const mantissa_t \fBmantissa\fP"
.br
.ti -1c
.RI "static constexpr const exponent_t \fBexponent\fP = F::exponent - COUNT::value"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F, typename COUNT>struct tml::floating::impl::shift< F, COUNT >"

.PP
Definition at line 130 of file float\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename F , typename COUNT > constexpr const mantissa_t \fBtml::floating::impl::shift\fP< F, COUNT >::mantissa\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= (COUNT::value >= 0) ? (F::mantissa << COUNT::value) :
                                                                                   (F::mantissa >> -COUNT::value)
.fi
.PP
Definition at line 132 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
