.TH "tml::runtime::scope_begin_action" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::runtime::scope_begin_action \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtml::runtime::scope_actions< E >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename F > \fBscope_begin_action\fP (F &&f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file raii_actions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
