.TH "tml::runtime::chameleon" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::runtime::chameleon \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtml::runtime::illformed_call< F, E >::void_return\fP, and \fBtml::runtime::placeholder< I >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > constexpr \fBoperator T\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBchameleon\fP &)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBchameleon\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file runtime_chameleon\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
