.TH "tml::div< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::div< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = tml::eval< \fBtml::mul\fP< \fBtml::floating::number\fP< S_LHS, E_LHS, M_LHS >, \fBtml::reciprocal\fP< \fBtml::floating::number\fP< S_RHS, E_RHS, M_RHS >> > >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<tml::floating::sign_t S_LHS, tml::floating::exponent_t E_LHS, tml::floating::mantissa_t M_LHS, tml::floating::sign_t S_RHS, tml::floating::exponent_t E_RHS, tml::floating::mantissa_t M_RHS>struct tml::div< tml::floating::number< S_LHS, E_LHS, M_LHS >, tml::floating::number< S_RHS, E_RHS, M_RHS > >"

.PP
Definition at line 405 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
