.TH "tml::impl::lambda_builder_2< ARGS >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::lambda_builder_2< ARGS > \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename ARGS>struct tml::impl::lambda_builder_2< ARGS >"

.PP
Definition at line 135 of file lambda\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
