.TH "tml::impl::foldr< F, STATE, tml::list< HEAD, TAIL...> >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::foldr< F, STATE, tml::list< HEAD, TAIL...> > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = tml::eval< F, HEAD, typename \fBfoldr\fP< F, STATE, \fBtml::list\fP< TAIL\&.\&.\&.>>::result >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTURBO_ENSURE_ALGEBRAIC_EVAL\fP (result)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F, typename STATE, typename HEAD, typename\&.\&.\&. TAIL>struct tml::impl::foldr< F, STATE, tml::list< HEAD, TAIL\&.\&.\&.> >"

.PP
Definition at line 205 of file high_order_functions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
