.TH "tml::impl::std_function_builder< R, ARGS >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::std_function_builder< R, ARGS > \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename R, typename ARGS>struct tml::impl::std_function_builder< R, ARGS >"

.PP
Definition at line 44 of file std_function\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
