.TH "tml::div< tml::fixed_point< INTEGER_T, LHS >, tml::fixed_point< INTEGER_T, RHS > >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::div< tml::fixed_point< INTEGER_T, LHS >, tml::fixed_point< INTEGER_T, RHS > > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::fixed_point< INTEGER_T,(LHS<< tml::impl::decimal_bits< INTEGER_T >::value)/RHS > >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename INTEGER_T, INTEGER_T LHS, INTEGER_T RHS>struct tml::div< tml::fixed_point< INTEGER_T, LHS >, tml::fixed_point< INTEGER_T, RHS > >"

.PP
Definition at line 177 of file fixed_point\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
