.TH "tml::impl::lazy_instance< L, ARGS >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::lazy_instance< L, ARGS > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< L >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename L, typename\&.\&.\&. ARGS>struct tml::impl::lazy_instance< L, ARGS >"

.PP
Definition at line 101 of file lazy\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
