.TH "tml::impl::multi_lambda< BODY, VARIABLES >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::multi_lambda< BODY, VARIABLES > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. ARGS> using \fBresult\fP = tml::eval< tml::multi_let< VARIABLES\&.\&.\&., ARGS\&.\&.\&., BODY > >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BODY, typename\&.\&.\&. VARIABLES>struct tml::impl::multi_lambda< BODY, VARIABLES >"

.PP
Definition at line 106 of file lambda\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
