.TH "tml::runtime::pipelined_function< S >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::runtime::pipelined_function< S > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. ARGS> tml::function_return_type< S > \fBoperator()\fP (ARGS &&\&.\&.\&.args)"
.br
.ti -1c
.RI "template<typename F > \fBpipelined_function\fP & \fBbegin\fP (F f)"
.br
.ti -1c
.RI "template<typename F > \fBpipelined_function\fP & \fBbody\fP (F f)"
.br
.ti -1c
.RI "template<typename F > \fBpipelined_function\fP & \fBend\fP (F f)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename S>struct tml::runtime::pipelined_function< S >"

.PP
Definition at line 37 of file pipelined_function\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
