.TH "tml::floating::impl::highest_set_bit< F, 0 >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::floating::impl::highest_set_bit< F, 0 > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = tml::size_t< 0 >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F>struct tml::floating::impl::highest_set_bit< F, 0 >"

.PP
Definition at line 110 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
