.TH "tml::impl::is_valid_call< tml::runtime::overloaded_function< F, Fs...>, ARGS...>" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::is_valid_call< tml::runtime::overloaded_function< F, Fs...>, ARGS...> \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< tml::any< tml::bind< tml::func::is_valid_call, _1, ARGS\&.\&.\&.>, tml::list< F, Fs\&.\&.\&.> > >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename F, typename\&.\&.\&. Fs, typename\&.\&.\&. ARGS>struct tml::impl::is_valid_call< tml::runtime::overloaded_function< F, Fs\&.\&.\&.>, ARGS\&.\&.\&.>"

.PP
Definition at line 74 of file overloaded_function\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
