.TH "tml::impl::std_function< F >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::std_function< F > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::impl::std_function_builder< tml::function_return_type< F >, tml::function_argumments< F > >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename F>struct tml::impl::std_function< F >"

.PP
Definition at line 51 of file std_function\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
