.TH "tml::impl::std_function_builder< R, tml::list< ARGS...> >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::std_function_builder< R, tml::list< ARGS...> > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< std::function< R(ARGS\&.\&.\&.)> >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename R, typename\&.\&.\&. ARGS>struct tml::impl::std_function_builder< R, tml::list< ARGS\&.\&.\&.> >"

.PP
Definition at line 47 of file std_function\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
