.TH "tml::impl::is_runtime_function< T >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::is_runtime_function< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::impl::is_functor< T >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct tml::impl::is_runtime_function< T >"

.PP
Definition at line 74 of file type_traits\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
