.TH "tml::impl::to_runtime< tml::floating::number< S, E, M > >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::to_runtime< tml::floating::number< S, E, M > > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr double \fBpow2\fP (std::int16_t e)"
.br
.ti -1c
.RI "static constexpr double \fBexecute\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<tml::floating::sign_t S, tml::floating::exponent_t E, tml::floating::mantissa_t M>struct tml::impl::to_runtime< tml::floating::number< S, E, M > >"

.PP
Definition at line 432 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
