.TH "tml::lists::impl::back< LIST, end >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::lists::impl::back< LIST, end > \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename LIST, bool end = false>struct tml::lists::impl::back< LIST, end >"

.PP
Definition at line 124 of file list_algorithms\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
