.TH "tml::floating::impl::highest_set_bit< tml::floating::number< S, E, 0 >, i >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::floating::impl::highest_set_bit< tml::floating::number< S, E, 0 >, i > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = tml::size_t< 0 >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<sign_t S, exponent_t E, std::size_t i>struct tml::floating::impl::highest_set_bit< tml::floating::number< S, E, 0 >, i >"

.PP
Definition at line 119 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
