.TH "tml::make_list< Ts >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::make_list< Ts > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< tml::list< Ts\&.\&.\&.> >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&. Ts>struct tml::make_list< Ts >"

.PP
Definition at line 66 of file list\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
