.TH "tml::impl::bind_call< B, CALL_ARGS >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::bind_call< B, CALL_ARGS > \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename B, typename\&.\&.\&. CALL_ARGS>struct tml::impl::bind_call< B, CALL_ARGS >"

.PP
Definition at line 48 of file bind\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
