.TH "tml::floating::impl::decimal_scinorm< MANTISSA, EXPONENT >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::floating::impl::decimal_scinorm< MANTISSA, EXPONENT > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBmantissa\fP = tml::integral_constant< std::int64_t, MANTISSA >"
.br
.ti -1c
.RI "using \fBexponent\fP = tml::integral_constant< std::int64_t, EXPONENT >"
.br
.ti -1c
.RI "using \fBexponent_bias\fP = tml::eval< \fBtml::log10\fP< mantissa >>"
.br
.ti -1c
.RI "using \fBexponent_biased\fP = tml::eval< \fBtml::sub\fP< exponent, exponent_bias >>"
.br
.ti -1c
.RI "using \fBresult\fP = typename \fBtml::floating::impl::decimal_sci\fP< MANTISSA, exponent_biased::value >::result"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<std::int64_t MANTISSA, std::int64_t EXPONENT = 0>struct tml::floating::impl::decimal_scinorm< MANTISSA, EXPONENT >"

.PP
Definition at line 614 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
