.TH "tml::impl::decimal< INTEGER_T, mantissa, exponent >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::decimal< INTEGER_T, mantissa, exponent > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< tml::eval< tml::mul< tml::pow< tml::adjusted_fixed_point< INTEGER_T, 10 >, tml::integral_constant< INTEGER_T, exponent > >, tml::adjusted_fixed_point< INTEGER_T, mantissa > > > >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename INTEGER_T, INTEGER_T mantissa, INTEGER_T exponent>struct tml::impl::decimal< INTEGER_T, mantissa, exponent >"

.PP
Definition at line 38 of file decimal\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
