.TH "tml::impl::apply_until< F, STATE, UNTIL >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::apply_until< F, STATE, UNTIL > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = typename \fBapply_while\fP< F, STATE, tml::lambda< \fBtml::placeholders::_1\fP, \fBtml::placeholders::_2\fP, \fBtml::logical_not\fP< \fBtml::deval\fP< UNTIL, \fBtml::placeholders::_1\fP, \fBtml::placeholders::_2\fP >>> >::result"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTURBO_ENSURE_ALGEBRAIC_EVAL\fP (result)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F, typename STATE, typename UNTIL>struct tml::impl::apply_until< F, STATE, UNTIL >"

.PP
Definition at line 117 of file algorithm\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
