.TH "tml::runtime::poly_container< BASE >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::runtime::poly_container< BASE > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , TURBO_ENABLE_FUNCTION_IF(std::is_base_of< BASE, T >) > void \fBinsert\fP (const T &elem)"
.br
.ti -1c
.RI "iterator \fBbegin\fP () const "
.br
.ti -1c
.RI "iterator \fBend\fP () const "
.br
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BASE>struct tml::runtime::poly_container< BASE >"

.PP
Definition at line 35 of file polymorphic_container\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
