.TH "tml::sqrt< N >::iteration< Xn, COUNTER >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::sqrt< N >::iteration< Xn, COUNTER > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = tml::eval< \fBtml::sub\fP< Xn, \fBtml::div\fP< \fBtml::sub\fP< \fBtml::mul\fP< Xn, Xn >, N >, \fBtml::add\fP< Xn, Xn >>>>"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename N>template<typename Xn, typename COUNTER>struct tml::sqrt< N >::iteration< Xn, COUNTER >"

.PP
Definition at line 71 of file math\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
