.TH "tml::runtime::scope_actions< E >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::runtime::scope_actions< E > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::runtime::scope_begin_action\fP, and \fBtml::runtime::scope_end_action< E >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename B , typename EE > \fBscope_actions\fP (B &&begin, EE &&end)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename E>struct tml::runtime::scope_actions< E >"

.PP
Definition at line 55 of file raii_actions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
