.TH "tml::reciprocal< tml::floating::number< S, E, M > >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::reciprocal< tml::floating::number< S, E, M > > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBN\fP = \fBtml::floating::number\fP< S, E, M >"
.br
.ti -1c
.RI "using \fBone\fP = tml::one< \fBtml::floating::number\fP< __, __, __ >>"
.br
.ti -1c
.RI "using \fBtwo\fP = \fBtml::floating::number\fP< tml::floating::sign_t::positive,-30, 0x80000000 >"
.br
.ti -1c
.RI "using \fBguess_divisor\fP = tml::floating::normalize< \fBN\fP, tml::size_t< 15 >>"
.br
.ti -1c
.RI "using \fBguess\fP = \fBtml::floating::number\fP< S,-guess_divisor::exponent-31, M/guess_divisor::mantissa >"
.br
.ti -1c
.RI "using \fBresult\fP = tml::apply_for< tml::lambda< \fB_1\fP, \fB_2\fP, \fBtml::mul\fP< \fB_1\fP, \fBtml::sub\fP< \fBtwo\fP, \fBtml::mul\fP< \fBN\fP, \fB_1\fP >>> >, \fBguess\fP, tml::size_t< 0 >, tml::size_t< tml::util::sizeof_bits< tml::floating::mantissa_t >::value/4 >>"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<tml::floating::sign_t S, tml::floating::exponent_t E, tml::floating::mantissa_t M>struct tml::reciprocal< tml::floating::number< S, E, M > >"

.PP
Definition at line 364 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
