.TH "tml::impl::function_signature< F >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::function_signature< F > \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsignature_extractor\fP"
.br
.ti -1c
.RI "struct \fBsignature_extractor< R(C::*)(ARGS\&.\&.\&.) const  >\fP"
.br
.ti -1c
.RI "struct \fBsignature_extractor< R(C::*)(ARGS\&.\&.\&.)>\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBreturn_type\fP = typename \fBsignature_extractor\fP< decltype(&F::operator())>::return_type"
.br
.ti -1c
.RI "using \fBargs\fP = typename \fBsignature_extractor\fP< decltype(&F::operator())>::args"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTURBO_ASSERT\fP ((tml::eval< \fBtml::impl::is_functor\fP< F >>),'ERROR: The type specified is not a \fBfunction\fP')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F>struct tml::impl::function_signature< F >"

.PP
Definition at line 98 of file type_traits\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
