.TH "tml::impl::multi_let_currifier< ARGS >::currify< list< CURRENT_VAR, VARS_TAIL...>, list< CURRENT_VAL, VALS_TAIL...>, nil >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::multi_let_currifier< ARGS >::currify< list< CURRENT_VAR, VARS_TAIL...>, list< CURRENT_VAL, VALS_TAIL...>, nil > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBnext_call\fP = \fBcurrify\fP< \fBlist\fP< VARS_TAIL\&.\&.\&.>, \fBlist\fP< VALS_TAIL\&.\&.\&.>>"
.br
.ti -1c
.RI "using \fBresult\fP = tml::let< CURRENT_VAR, CURRENT_VAL, typename next_call::result >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename ARGS>template<typename CURRENT_VAR, typename\&.\&.\&. VARS_TAIL, typename CURRENT_VAL, typename\&.\&.\&. VALS_TAIL>struct tml::impl::multi_let_currifier< ARGS >::currify< list< CURRENT_VAR, VARS_TAIL\&.\&.\&.>, list< CURRENT_VAL, VALS_TAIL\&.\&.\&.>, nil >"

.PP
Definition at line 280 of file let_expressions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
