.TH "tml::floating::impl::highest_set_bit< F, i >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::floating::impl::highest_set_bit< F, i > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = tml::size_t<(F::mantissa &(1U<< i))?i:highest_set_bit< F, i-1 >::result::value >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F, std::size_t i = tml::floating::mantissa_msb::value>struct tml::floating::impl::highest_set_bit< F, i >"

.PP
Definition at line 99 of file float\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
