.TH "tml::lists::impl::pop_front< tml::list< HEAD, TAIL...> >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::lists::impl::pop_front< tml::list< HEAD, TAIL...> > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< tml::list< TAIL\&.\&.\&.> >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename HEAD, typename\&.\&.\&. TAIL>struct tml::lists::impl::pop_front< tml::list< HEAD, TAIL\&.\&.\&.> >"

.PP
Definition at line 99 of file list_algorithms\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
