.TH "tml::impl::lambda< X, BODY >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::lambda< X, BODY > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "template<typename ARG > using \fBresult\fP = tml::eval< tml::let< X, ARG, BODY >>"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename X, typename BODY>struct tml::impl::lambda< X, BODY >"

.PP
Definition at line 47 of file lambda\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
