.TH "tml::runtime::scope_end_action< F >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::runtime::scope_end_action< F > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscope_end_action\fP (F &&f)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F>struct tml::runtime::scope_end_action< F >"

.PP
Definition at line 40 of file raii_actions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
