.TH "tml::log10< tml::integral_constant< T, V > >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::log10< tml::integral_constant< T, V > > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = tml::integral_constant< T, log >"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr const auto \fBvalue\fP = (std::uint64_t)V"
.br
.ti -1c
.RI "static constexpr const T \fBlog\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, T V>struct tml::log10< tml::integral_constant< T, V > >"

.PP
Definition at line 110 of file integral\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T , T V> constexpr const T \fBtml::log10\fP< tml::integral_constant< T, V > >::log\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= (0x0000000000000000ULL <= value && value < 0x000000000000000AULL) ? 0 :  
                                       (0x000000000000000AULL <= value && value < 0x0000000000000064ULL) ? 1 :  
                                       (0x0000000000000064ULL <= value && value < 0x00000000000003E8ULL) ? 2 :  
                                       (0x00000000000003E8ULL <= value && value < 0x0000000000002710ULL) ? 3 :  
                                       (0x0000000000002710ULL <= value && value < 0x00000000000186A0ULL) ? 4 :  
                                       (0x00000000000186A0ULL <= value && value < 0x00000000000F4240ULL) ? 5 :  
                                       (0x00000000000F4240ULL <= value && value < 0x0000000000989680ULL) ? 6 :  
                                       (0x0000000000989680ULL <= value && value < 0x0000000005F5E100ULL) ? 7 :  
                                       (0x0000000005F5E100ULL <= value && value < 0x000000003B9ACA00ULL) ? 8 :  
                                       (0x000000003B9ACA00ULL <= value && value < 0x00000002540BE400ULL) ? 9 :  
                                       (0x00000002540BE400ULL <= value && value < 0x000000174876E800ULL) ? 10 : 
                                       (0x000000174876E800ULL <= value && value < 0x000000E8D4A51000ULL) ? 11 : 
                                       (0x000000E8D4A51000ULL <= value && value < 0x000009184E72A000ULL) ? 12 : 
                                       (0x000009184E72A000ULL <= value && value < 0x00005AF3107A4000ULL) ? 13 : 
                                       (0x00005AF3107A4000ULL <= value && value < 0x00038D7EA4C68000ULL) ? 14 : 
                                       (0x00038D7EA4C68000ULL <= value && value < 0x002386F26FC10000ULL) ? 15 : 
                                       (0x002386F26FC10000ULL <= value && value < 0x016345785D8A0000ULL) ? 16 : 
                                       (0x016345785D8A0000ULL <= value && value < 0x0DE0B6B3A7640000ULL) ? 17 : 
                                                                                                           18
.fi
.PP
Definition at line 114 of file integral\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
