.TH "tml::lists::impl::pop_front< LIST >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::lists::impl::pop_front< LIST > \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename LIST>struct tml::lists::impl::pop_front< LIST >"

.PP
Definition at line 96 of file list_algorithms\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
