.TH "tml::impl::is_function< multi_lambda< BODY, VARIABLES...> >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::is_function< multi_lambda< BODY, VARIABLES...> > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr bool \fBresult\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&. VARIABLES, typename BODY>struct tml::impl::is_function< multi_lambda< BODY, VARIABLES\&.\&.\&.> >"

.PP
Definition at line 162 of file lambda\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
