.TH "tml::impl::map< T, BEGIN, END, tml::list< PROCESSED...> >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::map< T, BEGIN, END, tml::list< PROCESSED...> > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = typename \fBmap\fP< T, tml::iterator::next< BEGIN >, END, \fBtml::list\fP< PROCESSED\&.\&.\&., tml::eval< T, tml::iterator::deref< BEGIN >>> >::result"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTURBO_ENSURE_ALGEBRAIC_EVAL\fP (result)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename\&.\&.\&. PROCESSED, typename BEGIN, typename END>struct tml::impl::map< T, BEGIN, END, tml::list< PROCESSED\&.\&.\&.> >"

.PP
Definition at line 88 of file high_order_functions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
