.TH "tml::impl::apply_for< F, STATE, BEGIN, END, ADVANCE >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::impl::apply_for< F, STATE, BEGIN, END, ADVANCE > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBnext_state\fP = tml::eval< F, STATE, BEGIN >"
.br
.ti -1c
.RI "using \fBnext_counter\fP = tml::eval< ADVANCE, BEGIN >"
.br
.ti -1c
.RI "using \fBresult\fP = typename \fBapply_for\fP< F, next_state, next_counter, END, ADVANCE >::result"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTURBO_ENSURE_ALGEBRAIC_EVAL\fP (result)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename F, typename STATE, typename BEGIN, typename END, typename ADVANCE>struct tml::impl::apply_for< F, STATE, BEGIN, END, ADVANCE >"

.PP
Definition at line 57 of file algorithm\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
