.TH "tml::lists::impl::push_front< tml::list< Ts...>, T >" 3 "Fri Aug 22 2014" "Turbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tml::lists::impl::push_front< tml::list< Ts...>, T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtml::function< tml::list< T, Ts\&.\&.\&.> >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&. Ts, typename T>struct tml::lists::impl::push_front< tml::list< Ts\&.\&.\&.>, T >"

.PP
Definition at line 111 of file list_algorithms\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Turbo from the source code\&.
